### ISSUE TITLE
如何安装到已存在的viterpress站点

### ISSUE THREAD

**Issue by gezhaoyou** [chunge16/vitepress-blogs-theme#6]
你好，我有个已经存在的使用vitepress站点，想为站点添加blog页面，没大看明白你写的操作文档。
```bash
npm install -D vitepress @chunge16/vitepress-blogs-theme
```
之后需要怎么操作呢？文档讲的不是很清楚，还需要添加什么配置么？希望指导一下，谢谢

**Comment by chunge16** [comment]
这里有个使用模板，你可以看看[vitepress-blogs-theme-template.png]

2024年2月4日 20:59，Jaaron Ge ***@***.***> 写道：



你好，我有个已经存在的使用vitepress站点，想为站点添加blog页面，没大看明白你写的操作文档。

npm install -D vitepress @chunge16/vitepress-blogs-theme

之后需要怎么操作呢？文档讲的不是很清楚，还需要添加什么配置么？希望指导一下，谢谢

**Comment by chunge16** [comment]
已经存在的使用vitepress站点，安装该插件后，具体可以参考 [模板库](https://github.com/chunge16/vitepress-blogs-theme-template) 
1. 根目录新建 blog和里面的文件
2. 添加多个配置文件

**Comment by chunge16** [comment]
这里有个使用模板，你可以看看[vitepress-blogs-theme-template.png]

2024年2月4日 20:59，Jaaron Ge ***@***.***> 写道：



你好，我有个已经存在的使用vitepress站点，想为站点添加blog页面，没大看明白你写的操作文档。

npm install -D vitepress @chunge16/vitepress-blogs-theme

之后需要怎么操作呢？文档讲的不是很清楚，还需要添加什么配置么？希望指导一下，谢谢
